### ISSUE TITLE
SPJ似乎不能使用？

### ISSUE THREAD

**Issue by ghost** [Azure99/WinHustOJ#2]
在我这里使用Special Judge时，所有代码均会被评判为编译错误，关闭SPJ后又恢复正常，请问是否需要进行特殊配置才能使用SPJ？

**Comment by ghost** [comment]
并且日志记载了如下内容
```
[Judger.Core.Program.Internal.Entity.CompileException]
Message:Can not compile special judge program!
System.ComponentModel.Win32Exception (2): 系统找不到指定的文件。
   at System.Diagnostics.Process.StartWithCreateProcess(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at Judger.Utils.ProcessRunner.Run(String stdInput, String& stdOutput, String& stdError, ProcessPriorityClass priorityClass, Int32 inputDelay) in C:\Users\Azure99\Documents\Github\OpenJudger\src\Judger.Utils\ProcessRunner.cs:line 75
   at Judger.Core.Program.Internal.Compiler.Compile() in C:\Users\Azure99\Documents\Github\OpenJudger\src\Judger.Core\Program\Internal\Compiler.cs:line 49
Stack Trace:
   at Judger.Service.JudgeController.Judge(JudgeTask task) in C:\Users\Azure99\Documents\Github\OpenJudger\src\Judger.Service\JudgeController.cs:line 120
   at Judger.Service.JudgeController.RunJudgeTask(Object judgeTaskObject) in C:\Users\Azure99\Documents\Github\OpenJudger\src\Judger.Service\JudgeController.cs:line 80

-

```

**Comment by HeRaNO** [comment]
OpenJudger 并未正确获得 HUSTOJ 里的 SPJ，需要手动将 SPJ 源文件放在 OpenJudger 的 `TestData\<problem_id>\spj` 目录下，并且文件名必须为 `source`，比如 `source.cpp`。

BTW OpenJudger 只支持单文件编译。
